/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.inventorycontroller;
import model.ClothingItems;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Action extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Action.class.getName());
    private inventorycontroller controller;
    private AdminPage adminPage;

    
    /**
     * Creates new form Action
     */
    public Action(inventorycontroller controller, AdminPage adminPage) {
    this.controller = controller;
    this.adminPage = adminPage;
    initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IDL = new javax.swing.JLabel();
        NameL = new javax.swing.JLabel();
        CategoryL = new javax.swing.JLabel();
        SizeL = new javax.swing.JLabel();
        PriceL = new javax.swing.JLabel();
        StockL = new javax.swing.JLabel();
        IDTF = new javax.swing.JTextField();
        NameTF = new javax.swing.JTextField();
        SizeTF = new javax.swing.JTextField();
        PriceTF = new javax.swing.JTextField();
        StockTF = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(128, 0, 32));

        IDL.setForeground(new java.awt.Color(255, 255, 255));
        IDL.setText("ID");

        NameL.setForeground(new java.awt.Color(255, 255, 255));
        NameL.setText("Name");

        CategoryL.setForeground(new java.awt.Color(255, 255, 255));
        CategoryL.setText("Category");

        SizeL.setForeground(new java.awt.Color(255, 255, 255));
        SizeL.setText("Size");

        PriceL.setForeground(new java.awt.Color(255, 255, 255));
        PriceL.setText("Price");

        StockL.setForeground(new java.awt.Color(255, 255, 255));
        StockL.setText("Stock");

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saree", "Shawl", "Lehenga", "Kurti", "Topi", "Cholo" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(StockL, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StockTF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PriceL, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SizeL, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SizeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CategoryL, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameL, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDL, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(IDTF, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(NameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(SaveButton)
                        .addGap(41, 41, 41)
                        .addComponent(CancelButton)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IDL)
                    .addComponent(IDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameL)
                    .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CategoryL)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SizeL)
                    .addComponent(SizeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceL)
                    .addComponent(PriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StockL)
                    .addComponent(StockTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(CancelButton))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        try {
    
    if (NameTF.getText().isEmpty() ||
    SizeTF.getText().isEmpty() ||
    PriceTF.getText().isEmpty() ||
    StockTF.getText().isEmpty()) {

    JOptionPane.showMessageDialog(this, "All fields are required");
    return;
}


    int id = Integer.parseInt(IDTF.getText());
    double price = Double.parseDouble(PriceTF.getText());
    int stock = Integer.parseInt(StockTF.getText());

    String name = NameTF.getText().trim();
    String category = jComboBox1.getSelectedItem().toString();
    String size = SizeTF.getText().trim();

    // 3. Length validation
    if (name.length() > 50) {
        JOptionPane.showMessageDialog(this, "Item name must be less than 50 characters");
        return;
    }
    if (!size.matches("S|M|L|XL|XXL")) {
        JOptionPane.showMessageDialog(this, "Size must be S, M, L, XL, or XXL");
        return;
    }

    if (price <= 0 || stock < 0) {
        JOptionPane.showMessageDialog(this, "Price must be positive and stock cannot be negative");
        return;
    }

    if (controller.isDuplicateItem(name, id)) {
        JOptionPane.showMessageDialog(this, "Item with this name already exists");
        return;
    }

   
    if (controller.getItemById(id) == null) {
        controller.addItem(name, category, size, price, stock);
        JOptionPane.showMessageDialog(this, "Item added successfully");
    } else {
        controller.updateItem(id, name, category, size, price, stock);
        JOptionPane.showMessageDialog(this, "Item updated successfully");
    }

    adminPage.loadInventoryTable();
    this.dispose();

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Invalid number format in ID");
}

    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    public void setFields(ClothingItems item) {
    IDTF.setText(String.valueOf(item.getId()));
    NameTF.setText(item.getName());
    jComboBox1.setSelectedItem(item.getCategory());
    SizeTF.setText(item.getSize());
    PriceTF.setText(String.valueOf(item.getPrice()));
    StockTF.setText(String.valueOf(item.getStock()));

    IDTF.setEditable(false); // important
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CategoryL;
    private javax.swing.JLabel IDL;
    private javax.swing.JTextField IDTF;
    private javax.swing.JLabel NameL;
    private javax.swing.JTextField NameTF;
    private javax.swing.JLabel PriceL;
    private javax.swing.JTextField PriceTF;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel SizeL;
    private javax.swing.JTextField SizeTF;
    private javax.swing.JLabel StockL;
    private javax.swing.JTextField StockTF;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
