/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import model.ClothingItems;
import controller.inventorycontroller;
import controller.OrderController;
import javax.swing.JOptionPane;
import model.Order;


/**
 *
 * @author User
 */
public class AdminPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminPage.class.getName());
   private final inventorycontroller controller;
   private final OrderController orderController;

    /**
     * Creates new form AdminPage
     */
    public AdminPage(inventorycontroller controller, OrderController orderController) {
    initComponents();
    this.controller = controller;
    this.orderController = orderController;
    loadDashboard();
    loadRecentProductsTable();
    loadInventoryTable();
}

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        DashboardButton = new javax.swing.JButton();
        InventoryButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        logoandnamePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        OrderButton = new javax.swing.JButton();
        RightPanel = new javax.swing.JPanel();
        DashboardPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TotalProducts = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TotalOrders = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        RecentProductsTable1 = new javax.swing.JTable();
        InventoryPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InventoryTable = new javax.swing.JTable();
        CreateButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        SearchButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        SortByIDButton = new javax.swing.JButton();
        SortByNameButton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        SearchButton2 = new javax.swing.JButton();
        OrderPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        RemoveLastOrder = new javax.swing.JButton();
        DeleteSelectedOrder = new javax.swing.JButton();
        SearchButton3 = new javax.swing.JButton();
        SearchButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        LeftPanel.setBackground(new java.awt.Color(128, 0, 32));

        DashboardButton.setText("Dashboard");
        DashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardButtonActionPerformed(evt);
            }
        });

        InventoryButton.setText("Inventory");
        InventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryButtonActionPerformed(evt);
            }
        });

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        logoandnamePanel.setBackground(new java.awt.Color(128, 0, 32));
        logoandnamePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        logoandnamePanel.setPreferredSize(new java.awt.Dimension(118, 87));

        jLabel3.setFont(new java.awt.Font("Palace Script MT", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alum");

        javax.swing.GroupLayout logoandnamePanelLayout = new javax.swing.GroupLayout(logoandnamePanel);
        logoandnamePanel.setLayout(logoandnamePanelLayout);
        logoandnamePanelLayout.setHorizontalGroup(
            logoandnamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoandnamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(14, 14, 14))
        );
        logoandnamePanelLayout.setVerticalGroup(
            logoandnamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoandnamePanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(16, 16, 16))
        );

        OrderButton.setText("Orders");
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OrderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(logoandnamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addComponent(logoandnamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(DashboardButton)
                .addGap(18, 18, 18)
                .addComponent(InventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(21, 21, 21))
        );

        jPanel5.add(LeftPanel);

        RightPanel.setLayout(new java.awt.CardLayout());

        DashboardPanel.setBackground(new java.awt.Color(234, 224, 213));

        jPanel2.setBackground(new java.awt.Color(205, 181, 156));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Admin Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(15, 15, 15))
        );

        jLabel1.setText("Products Available");

        javax.swing.GroupLayout TotalProductsLayout = new javax.swing.GroupLayout(TotalProducts);
        TotalProducts.setLayout(TotalProductsLayout);
        TotalProductsLayout.setHorizontalGroup(
            TotalProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        TotalProductsLayout.setVerticalGroup(
            TotalProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalProductsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Total Orders");

        javax.swing.GroupLayout TotalOrdersLayout = new javax.swing.GroupLayout(TotalOrders);
        TotalOrders.setLayout(TotalOrdersLayout);
        TotalOrdersLayout.setHorizontalGroup(
            TotalOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        TotalOrdersLayout.setVerticalGroup(
            TotalOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalOrdersLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("Recently Added Products");

        RecentProductsTable1.setBackground(new java.awt.Color(242, 242, 242));
        RecentProductsTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Size", "Price", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RecentProductsTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(RecentProductsTable1);
        if (RecentProductsTable1.getColumnModel().getColumnCount() > 0) {
            RecentProductsTable1.getColumnModel().getColumn(0).setResizable(false);
            RecentProductsTable1.getColumnModel().getColumn(1).setResizable(false);
            RecentProductsTable1.getColumnModel().getColumn(2).setResizable(false);
            RecentProductsTable1.getColumnModel().getColumn(3).setResizable(false);
            RecentProductsTable1.getColumnModel().getColumn(4).setResizable(false);
            RecentProductsTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout DashboardPanelLayout = new javax.swing.GroupLayout(DashboardPanel);
        DashboardPanel.setLayout(DashboardPanelLayout);
        DashboardPanelLayout.setHorizontalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addGroup(DashboardPanelLayout.createSequentialGroup()
                        .addComponent(TotalProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(TotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)))
                .addGap(52, 52, 52))
            .addGroup(DashboardPanelLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DashboardPanelLayout.setVerticalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TotalOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        RightPanel.add(DashboardPanel, "card4");

        InventoryPanel.setBackground(new java.awt.Color(234, 224, 213));

        InventoryTable.setBackground(new java.awt.Color(242, 242, 242));
        InventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Size", "Price", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        InventoryTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(InventoryTable);
        if (InventoryTable.getColumnModel().getColumnCount() > 0) {
            InventoryTable.getColumnModel().getColumn(0).setResizable(false);
            InventoryTable.getColumnModel().getColumn(1).setResizable(false);
            InventoryTable.getColumnModel().getColumn(2).setResizable(false);
            InventoryTable.getColumnModel().getColumn(3).setResizable(false);
            InventoryTable.getColumnModel().getColumn(4).setResizable(false);
            InventoryTable.getColumnModel().getColumn(5).setResizable(false);
        }

        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(205, 181, 156));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Products");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(15, 15, 15))
        );

        SearchButton1.setText("Linear Search");
        SearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton1ActionPerformed(evt);
            }
        });

        SortByIDButton.setText("Sort By ID");
        SortByIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortByIDButtonActionPerformed(evt);
            }
        });

        SortByNameButton.setText("Sort By Name");
        SortByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortByNameButtonActionPerformed(evt);
            }
        });

        SearchButton2.setText("Binary Search");
        SearchButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InventoryPanelLayout = new javax.swing.GroupLayout(InventoryPanel);
        InventoryPanel.setLayout(InventoryPanelLayout);
        InventoryPanelLayout.setHorizontalGroup(
            InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventoryPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventoryPanelLayout.createSequentialGroup()
                .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InventoryPanelLayout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InventoryPanelLayout.createSequentialGroup()
                        .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(InventoryPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InventoryPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(SortByIDButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SortByNameButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SearchButton1)
                            .addComponent(SearchButton2))))
                .addGap(31, 31, 31))
        );
        InventoryPanelLayout.setVerticalGroup(
            InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryPanelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SearchButton1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SortByNameButton)
                        .addComponent(SortByIDButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        RightPanel.add(InventoryPanel, "card3");

        OrderPanel.setBackground(new java.awt.Color(234, 224, 213));

        jPanel3.setBackground(new java.awt.Color(205, 181, 156));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Orders");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addContainerGap(527, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(15, 15, 15))
        );

        OrderTable.setBackground(new java.awt.Color(242, 242, 242));
        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "User Name", "Phone", "Address", "Item Name", "Quantity", "Total ", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OrderTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(OrderTable);
        if (OrderTable.getColumnModel().getColumnCount() > 0) {
            OrderTable.getColumnModel().getColumn(0).setResizable(false);
            OrderTable.getColumnModel().getColumn(1).setResizable(false);
            OrderTable.getColumnModel().getColumn(2).setResizable(false);
            OrderTable.getColumnModel().getColumn(3).setResizable(false);
            OrderTable.getColumnModel().getColumn(4).setResizable(false);
            OrderTable.getColumnModel().getColumn(5).setResizable(false);
            OrderTable.getColumnModel().getColumn(6).setResizable(false);
            OrderTable.getColumnModel().getColumn(7).setResizable(false);
        }

        RemoveLastOrder.setText("Remove Last Order");
        RemoveLastOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveLastOrderActionPerformed(evt);
            }
        });

        DeleteSelectedOrder.setText("Delete");
        DeleteSelectedOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSelectedOrderActionPerformed(evt);
            }
        });

        SearchButton3.setText("Linear Search");
        SearchButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton3ActionPerformed(evt);
            }
        });

        SearchButton4.setText("Binary Search");
        SearchButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrderPanelLayout = new javax.swing.GroupLayout(OrderPanel);
        OrderPanel.setLayout(OrderPanelLayout);
        OrderPanelLayout.setHorizontalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(RemoveLastOrder)
                .addGap(115, 115, 115)
                .addComponent(DeleteSelectedOrder)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OrderPanelLayout.createSequentialGroup()
                        .addComponent(SearchButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OrderPanelLayout.createSequentialGroup()
                        .addComponent(SearchButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        OrderPanelLayout.setVerticalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveLastOrder)
                    .addComponent(DeleteSelectedOrder))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        RightPanel.add(OrderPanel, "orderPanel");

        jPanel5.add(RightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        this.dispose();
    new LoginPage(controller, orderController).setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void DashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardButtonActionPerformed
        CardLayout cl = (CardLayout)(RightPanel.getLayout());
        cl.show(RightPanel, "card4");
        loadDashboard();
        loadRecentProductsTable();
    }//GEN-LAST:event_DashboardButtonActionPerformed

    private void loadDashboard() {
    jLabel1.setText("Products Available: " + controller.getInventory().size());
    jLabel7.setText("Total Orders: " + orderController.getOrders().size());
}
    private void loadRecentProductsTable() {
    DefaultTableModel model =
        (DefaultTableModel) RecentProductsTable1.getModel();

    model.setRowCount(0);

    for (ClothingItems item : controller.getRecentItems()) {
        model.addRow(new Object[]{
            item.getId(),
            item.getName(),
            item.getCategory(),
            item.getSize(),
            item.getPrice(),
            item.getStock()
        });
    }
}


    
    private void InventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryButtonActionPerformed
       CardLayout cl = (CardLayout)(RightPanel.getLayout());
       cl.show(RightPanel, "card3"); // TODO add your handling code here:
    }//GEN-LAST:event_InventoryButtonActionPerformed

    

     public void loadInventoryTable() {
    DefaultTableModel model = (DefaultTableModel) InventoryTable.getModel();
    model.setRowCount(0); // clear existing rows

    for (ClothingItems item : controller.getInventory()) {
        model.addRow(new Object[]{
            item.getId(),
            item.getName(),
            item.getCategory(),
            item.getSize(),
            item.getPrice(),
            item.getStock()
        });
    }
}

    

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        Action actionFrame = new Action(controller,this);
        actionFrame.setVisible(true);
    }//GEN-LAST:event_CreateButtonActionPerformed
   


    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        int selectedRow = InventoryTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select an item first!");
        return;
    }

    int id = (int) InventoryTable.getValueAt(selectedRow, 0);
    ClothingItems item = controller.getItemById(id);

    Action actionFrame = new Action(controller,this);
    actionFrame.setFields(item);   // fills form from selected row
    actionFrame.setVisible(true);
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int selectedRow = InventoryTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select an item to delete!");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete this item?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        int id = (int) InventoryTable.getValueAt(selectedRow, 0);
        controller.deleteItem(id);
        loadInventoryTable();   // refresh table
        JOptionPane.showMessageDialog(this, "Item deleted successfully!");
    }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
       CardLayout cl = (CardLayout)(RightPanel.getLayout());
       cl.show(RightPanel, "orderPanel"); 
       loadOrdersTable();
    }//GEN-LAST:event_OrderButtonActionPerformed

    public void loadOrdersTable() {
    DefaultTableModel model = (DefaultTableModel) OrderTable.getModel();
    model.setRowCount(0);

    for (Order order : orderController.getOrders()) {
        model.addRow(new Object[]{
            order.getOrderId(),
            order.getCustomerName(),
            order.getPhone(),
            order.getAddress(),
            order.getItemName(),
            order.getQuantity(),
            order.getTotal(),
            order.getDate()
        });
    }
}
    private void SearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton1ActionPerformed
        String key = jTextField1.getText().trim();

    if (key.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter product name!");
        return;
    }

    DefaultTableModel model =
            (DefaultTableModel) InventoryTable.getModel();
    model.setRowCount(0);

    boolean found = false;

    for (ClothingItems item : controller.getInventory()) {
        if (item.getName().equalsIgnoreCase(key)) {
            model.addRow(new Object[]{
                item.getId(),
                item.getName(),
                item.getCategory(),
                item.getSize(),
                item.getPrice(),
                item.getStock()
            });
            found = true;
            break;
        }
    }

    if (!found) {
        JOptionPane.showMessageDialog(this, "Item not found!");
    }
    }//GEN-LAST:event_SearchButton1ActionPerformed

    private void RemoveLastOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveLastOrderActionPerformed
        if (orderController.getOrders().isEmpty()) {
        JOptionPane.showMessageDialog(this, "No orders to remove!");
        return;
    }

    orderController.removeLastOrder(); // pop()
    loadOrdersTable();

    JOptionPane.showMessageDialog(this, "Last order removed ");
    }//GEN-LAST:event_RemoveLastOrderActionPerformed

    private void DeleteSelectedOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSelectedOrderActionPerformed
        int row = OrderTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select an order first!");
        return;
    }

    int orderId = (int) OrderTable.getValueAt(row, 0);

    orderController.getOrders().removeIf(o -> o.getOrderId() == orderId);

    loadOrdersTable();
    JOptionPane.showMessageDialog(this, "Order deleted!");        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteSelectedOrderActionPerformed

    private void SortByIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortByIDButtonActionPerformed
         selectionSortById();
    }//GEN-LAST:event_SortByIDButtonActionPerformed

    private void SortByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortByNameButtonActionPerformed
        selectionSortByName();
    }//GEN-LAST:event_SortByNameButtonActionPerformed

    //BinarySearch
    
    private int binarySearchByName(String key) {

    var items = controller.getInventory();

    int low = 0;
    int high = items.size() - 1;

    while (low <= high) {

        int mid = (low + high) / 2;

        int result =
                items.get(mid).getName().compareToIgnoreCase(key);

        if (result == 0) {
            return mid;        // FOUND
        } else if (result < 0) {
            low = mid + 1;     // RIGHT
        } else {
            high = mid - 1;    // LEFT
        }
    }

    return -1; // NOT FOUND
}

    
    private void SearchButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton2ActionPerformed
        String key = jTextField2.getText().trim();

    if (key.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter product name!");
        return;
    }

    selectionSortByName();

    int index = binarySearchByName(key);

    DefaultTableModel model =
            (DefaultTableModel) InventoryTable.getModel();
    model.setRowCount(0);

    if (index != -1) {
        ClothingItems item = controller.getInventory().get(index);
        model.addRow(new Object[]{
            item.getId(),
            item.getName(),
            item.getCategory(),
            item.getSize(),
            item.getPrice(),
            item.getStock()
        });
    } else {
        JOptionPane.showMessageDialog(this, "Item not found!");
    }
    }//GEN-LAST:event_SearchButton2ActionPerformed

    private void SearchButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton3ActionPerformed
        String input = jTextField4.getText().trim();

    if (input.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Order ID!");
        return;
    }

    int key;
    try {
        key = Integer.parseInt(input);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Order ID must be a number!");
        return;
    }

    DefaultTableModel model =
            (DefaultTableModel) OrderTable.getModel();
    model.setRowCount(0);

    boolean found = false;

    for (Order order : orderController.getOrders()) {
        if (order.getOrderId() == key) {
            model.addRow(new Object[]{
                order.getOrderId(),
                order.getCustomerName(),
                order.getPhone(),
                order.getAddress(),
                order.getItemName(),
                order.getQuantity(),
                order.getTotal(),
                order.getDate()
            });
            found = true;
            break; // true linear search
        }
    }

    if (!found) {
        JOptionPane.showMessageDialog(this, "Order not found!");
    }
    }//GEN-LAST:event_SearchButton3ActionPerformed
    
    private void selectionSortOrdersByName() {

    var orders = orderController.getOrders();
    int n = orders.size();

    for (int i = 0; i < n - 1; i++) {

        int minIndex = i;

        for (int j = i + 1; j < n; j++) {
            if (orders.get(j).getItemName()
                    .compareToIgnoreCase(
                            orders.get(minIndex).getItemName()
                    ) < 0) {
                minIndex = j;
            }
        }

        // swap
        Order temp = orders.get(minIndex);
        orders.set(minIndex, orders.get(i));
        orders.set(i, temp);
    }

    loadOrdersTable();
}

    
    private void SearchButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton4ActionPerformed
        String key = jTextField3.getText().trim();

    if (key.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter item name!");
        return;
    }

    // IMPORTANT: SORT FIRST
    selectionSortOrdersByName();

    int index = binarySearchOrderByName(key);

    DefaultTableModel model =
            (DefaultTableModel) OrderTable.getModel();
    model.setRowCount(0);

    if (index != -1) {
        Order order = orderController.getOrders().get(index);
        model.addRow(new Object[]{
            order.getOrderId(),
            order.getCustomerName(),
            order.getPhone(),
            order.getAddress(),
            order.getItemName(),
            order.getQuantity(),
            order.getTotal(),
            order.getDate()
        });
    } else {
        JOptionPane.showMessageDialog(this, "Order not found!");
    }
    }//GEN-LAST:event_SearchButton4ActionPerformed

    private int binarySearchOrderByName(String key) {

    var orders = orderController.getOrders();

    int low = 0;
    int high = orders.size() - 1;

    while (low <= high) {

        int mid = (low + high) / 2;

        int result =
                orders.get(mid).getItemName()
                        .compareToIgnoreCase(key);

        if (result == 0) {
            return mid;
        } else if (result < 0) {
            low = mid + 1;
        } else {
            high = mid - 1;
        }
    }

    return -1;
}

 private void selectionSortById() {

    var items = controller.getInventory();
    int n = items.size();

    for (int i = 0; i < n - 1; i++) {

        int minIndex = i;

        for (int j = i + 1; j < n; j++) {
            if (items.get(j).getId() < items.get(minIndex).getId()) {
                minIndex = j;
            }
        }

        // swap
        ClothingItems temp = items.get(minIndex);
        items.set(minIndex, items.get(i));
        items.set(i, temp);
    }

    loadInventoryTable();
}

 private void selectionSortByName() {

    var items = controller.getInventory();
    int n = items.size();

    for (int i = 0; i < n - 1; i++) {

        int minIndex = i;

        for (int j = i + 1; j < n; j++) {
            if (items.get(j).getName()
                    .compareToIgnoreCase(items.get(minIndex).getName()) < 0) {
                minIndex = j;
            }
        }

        // swap
        ClothingItems temp = items.get(minIndex);
        items.set(minIndex, items.get(i));
        items.set(i, temp);
    }

    loadInventoryTable();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton DashboardButton;
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DeleteSelectedOrder;
    private javax.swing.JButton InventoryButton;
    private javax.swing.JPanel InventoryPanel;
    private javax.swing.JTable InventoryTable;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton OrderButton;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JTable OrderTable;
    private javax.swing.JTable RecentProductsTable1;
    private javax.swing.JButton RemoveLastOrder;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JButton SearchButton1;
    private javax.swing.JButton SearchButton2;
    private javax.swing.JButton SearchButton3;
    private javax.swing.JButton SearchButton4;
    private javax.swing.JButton SortByIDButton;
    private javax.swing.JButton SortByNameButton;
    private javax.swing.JPanel TotalOrders;
    private javax.swing.JPanel TotalProducts;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel logoandnamePanel;
    // End of variables declaration//GEN-END:variables
}
